---
- hosts: all
  vars:
    mysql_root_pass: "{{ lookup('env','MYSQL_ROOT_PASSWORD') }}" 
  tasks:
    - name: "testing echo"
      shell: echo "hello world"
    - name: "updating cache"
      shell: apk update
    - name: "installing vim"
      apk: 
        name: vim
        state: present
        update_cache: yes
    - name: Install Mysql
      apk: 
        name: mysql
        state: latest
    - name: Instal mysql client
      apk:
        name: mysql-client
        state: latest
    - name: create socket directory
      file: 
          path: /run/mysqld
          owner: mysql
          group: mysql
          state: directory
    - name: create db
      shell: /usr/bin/mysql_install_db --user=mysql
    - name: create users and schema
      shell: cat create_db | /usr/bin/mysqld --user=mysql --bootstrap --verbose=0
    - name: start db
      shell: /usr/bin/mysqld --user=mysql &
